from typing import Any

from workflows.chatbot_workflow import ChatbotWorkflow


class ChatbotService:
    """Exposes chatbot operations to application interfaces.

    Attributes:
        workflow: Workflow responsible for processing chatbot operations.
    """

    def __init__(
        self,
        workflow: ChatbotWorkflow,
    ) -> None:
        """Initialize the chatbot service.

        Args:
            workflow: Workflow responsible for chatbot message processing.
        """
        self.workflow = workflow

    def process_message(
        self,
        message: str,
    ) -> str:
        """Process a user message through the chatbot workflow.

        Args:
            message: Message submitted by the user.

        Returns:
            Response generated by the chatbot.
        """
        return self.workflow.process_message(message)

    def get_messages(
        self,
    ) -> list[dict[str, Any]]:
        """Return the conversation messages from the current session.

        Returns:
            Stored conversation messages.
        """
        return self.workflow.get_messages()

    def get_last_result(
        self,
    ) -> float | None:
        """Return the last mathematical result from the current session.

        Returns:
            Last result or None when no calculation has been performed.
        """
        return self.workflow.get_last_result()

    def clear_memory(
        self,
    ) -> None:
        """Clear all data stored in the current chatbot session."""
        self.workflow.clear_memory()
