from typing import Any

from pydantic import BaseModel, Field


class ChatRequest(BaseModel):
    """Represents the payload required to process a chatbot message.

    Attributes:
        message: Message submitted by the user.
    """

    message: str = Field(
        min_length=1,
        description="Message submitted to the chatbot.",
        examples=["What is 5 + 5?"],
    )


class ChatResponseData(BaseModel):
    """Represents the data returned after processing a message.

    Attributes:
        response: Response generated by the chatbot.
        messages: Complete conversation history.
        last_result: Last mathematical result stored in the session.
    """

    response: str
    messages: list[dict[str, Any]]
    last_result: float | None


class ChatResponse(BaseModel):
    """Represents a successful chatbot API response.

    Attributes:
        success: Indicates whether the operation succeeded.
        message: Human-readable operation description.
        data: Chatbot processing result.
    """

    success: bool
    message: str
    data: ChatResponseData


class ClearMemoryResponse(BaseModel):
    """Represents the response returned after clearing chatbot memory.

    Attributes:
        success: Indicates whether the operation succeeded.
        message: Human-readable operation description.
    """

    success: bool
    message: str
